### PR TITLE
Component upgrades

### PR DESCRIPTION
**Pull request by BirdHighway**
Adds the `@blendededge/ferryman-extensions` library to enable passthrough functionality.

### CODE REVIEW

**Comment by winklerj** [comment]
Can you also update the Github Action workflows to tag the docker images appropriately?

**Comment by BirdHighway** [comment]
Tests appear to be have been broken before update. Would you like me to fix?

**Comment by winklerj** [comment]
I logged an issue to fix the tests https://github.com/blendededge/filter-component-oih/issues/8. Let's defer fixing them for now.

**Review by winklerj — APPROVED** [review]

**Comment by winklerj** [comment]
Also the other workflows would need updated with the same tagging logic for that part to be complete. Approving anyway to move this forward

**Pull request merged**
